version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    shm_size: '2gb'
  tests:
    build: .
    command: pytest tests
    depends_on:
      - selenium
