services:
  chrome:
    image: selenium/standalone-chromium:latest
    ports:
      - 4444:4444
    shm_size: '2gb'
    networks:
      - host

  tests:
    build: .
    command: pytest tests
    depends_on:
      - selenium
    networks:
      - host

networks:
  host: {}
