name: Integration Tests

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size="2g"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Docker
      run: |
        docker compose build
        docker compose up -e
