name: Integration Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size="2g"


    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Pyhon
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest tests --selenium http://selenium:4444/wd/hub
