name: Integration Tests

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check docker
      run: |
        docker ps

    - name: Setup Docker
      run: |
        docker compose build
        docker compose up
